### PR TITLE
fix bm_tornado_http

### LINKED ISSUE #55: tornado benchmark fails on Python 3.8.0a4+
```
  File "/home/haypo/performance/performance/benchmarks/bm_tornado_http.py", line 60, in bench_tornado
    sock = make_http_server(make_application())
  File "/home/haypo/performance/performance/benchmarks/bm_tornado_http.py", line 54, in make_http_server
    server.add_sockets(sockets)
  File "lib/python3.8/site-packages/tornado/tcpserver.py", line 157, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "lib/python3.8/site-packages/tornado/netutil.py", line 268, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "lib/python3.8/site-packages/tornado/platform/asyncio.py", line 76, in add_handler
    raise ValueError("fd %s added twice" % fd)
fd 3 added twice
```

### PR DESCRIPTION
**Pull request by methane**
fixes #55

### CODE REVIEW

**Comment by vstinner** [comment]
Can you please also reenable the test? I disabled it in performance/benchmarks/__init_.py.

**Comment by vstinner** [comment]
I confirm that bm_tornado_http.py doesn't crash anymore on Python 3.8.0a4+. Thanks for the fix @methane!

FYI many warnings are logged with a Python compiled in debug mode:

```
vstinner@apu$ env/bin/python performance/benchmarks/bm_tornado_http.py  -v
/home/vstinner/prog/python/performance/env/lib/python3.8/site-packages/tornado/httputil.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  class HTTPHeaders(collections.MutableMapping):
/home/vstinner/prog/python/performance/env/lib/python3.8/site-packages/tornado/httputil.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  class HTTPHeaders(collections.MutableMapping):
/home/vstinner/prog/python/performance/env/lib/python3.8/site-packages/tornado/gen.py:650: DeprecationWarning: gen.Task is deprecated, use Futures instead
  warnings.warn("gen.Task is deprecated, use Futures instead",
/home/vstinner/prog/python/performance/env/lib/python3.8/site-packages/tornado/stack_context.py:196: DeprecationWarning: StackContext is deprecated and will be removed in Tornado 6.0
  warnings.warn(
/home/vstinner/prog/python/performance/env/lib/python3.8/site-packages/tornado/http1connection.py:405: DeprecationWarning: callback argument is deprecated, use returned Future instead
  warnings.warn("callback argument is deprecated, use returned Future instead",
/home/vstinner/prog/python/performance/env/lib/python3.8/site-packages/tornado/http1connection.py:446: DeprecationWarning: callback argument is deprecated, use returned Future instead
  warnings.warn("callback argument is deprecated, use returned Future instead",
```

**Comment by methane** [comment]
These warnings are raised because this benchmark uses deprecated APIs for
Python 2 compatibility.

Tornado 6 is released already and it dropped Python 2 support.
Maybe, it's time to drop Python 2 support in some benchmarks including Django?

Comparing performance between Python 2 and 3 is less important than before.

**Comment by vstinner** [comment]
> Maybe, it's time to drop Python 2 support in some benchmarks including Django?

I would prefer to keep Python 2 support until Python 2.7 reachs its end-of-life (end of the year).

You're right than Django and Tornado explicitly request an old version which is still compatible with Python 2, on purpose.

**Pull request merged**
